
version: '3.8'

services:
  client:
    build:
      context: ./client          
      dockerfile: Dockerfile    
    ports:
      - "8000:8000"             
    environment:
      - PORT=8000               
    depends_on:
      - server 

  server:
    build:
      context: ./server          
      dockerfile: Dockerfile    
    ports:
      - "3000:3000"             
    environment:
      - MONGO_HOST=database     
      - MONGO_PORT=27017        
    depends_on:
      - database                

  database:
    image: mongo:latest          
    ports:
      - "27017:27017"           
    volumes:
      - mongodb_data:/data/db   
volumes:
  mongodb_data:                 